#!/usr/bin/env python3
"""
Basic System Monitor Script
Checks CPU usage, memory, disk space, and running processes
Works on macOS, Linux, and Windows
"""

import psutil
import platform
import datetime
import os
import time

def get_system_info():
    """Get basic system information"""
    info = {
        'system': platform.system(),
        'node': platform.node(),
        'release': platform.release(),
        'version': platform.version(),
        'machine': platform.machine(),
        'processor': platform.processor()
    }
    return info

def get_cpu_usage():
    """Get CPU usage percentage"""
    cpu_percent = psutil.cpu_percent(interval=1)
    cpu_count = psutil.cpu_count()
    return cpu_percent, cpu_count

def get_memory_usage():
    """Get detailed memory usage information"""
    memory = psutil.virtual_memory()
    return {
        'total': memory.total,
        'available': memory.available,
        'percent': memory.percent,
        'used': memory.used,
        'free': memory.free,
        'active': memory.active,
        'inactive': memory.inactive,
        'wired': memory.wired
    }

# def get_disk_usage():  ## original code generated by Claude, this was buggy as it did not display proper disk usage
#    """Get disk usage for the root directory"""
#    disk = psutil.disk_usage('/')
#    return {
#        'total': disk.total,
#        'used': disk.used,
#        'free': disk.free,
#        'percent': (disk.used / disk.total) * 100
#    }

# def get_disk_usage():  ##debug code recommended by Llama 3.3 
#    """Get disk usage for the root directory"""
#    disk = psutil.disk_usage('/')
#    return {
#        'total': disk.total,
#        'used': disk.used,
#        'free': disk.free,
#        'percent': disk.percent
#    }

#def get_disk_usage():  ## second attempt at debugging by Llama 3.3
#    """Get disk usage for the root directory"""
#    disk = psutil.disk_usage('/')
#    print(f"Raw disk usage values:")
#    print(f"Total: {disk.total} bytes")
#    print(f"Used: {disk.used} bytes")
#    print(f"Free: {disk.free} bytes")
#    print(f"Percent: {disk.percent}%")
#    return {
#        'total': disk.total,
#        'used': disk.used,
#        'free': disk.free,
#        'percent': disk.percent
#    }

def get_disk_usage(): ## third attempt at debugging by Llama 3.3, this time using psutil.disk.partitions
    """Get disk usage for all partitions"""
    partitions = psutil.disk_partitions()
    for partition in partitions:
        print(f"Partition: {partition.mountpoint}")
        try: ## added as part of fourth attempt
            disk = psutil.disk_usage(partition.mountpoint)
            print(f"Total: {bytes_to_gb(disk.total):.1f} GB")
            print(f"Used: {bytes_to_gb(disk.used):.1f} GB ({disk.percent:.1f}%)")
            print(f"Free: {bytes_to_gb(disk.free):.1f} GB")
        except Exception as e: ## added as fourth attempt
            print(f"Error: {e}") ## added as fourth attempt
        print()

def get_top_processes(limit=5):
    """Get top processes by CPU usage"""
    processes = []
    
    # First pass: initialize CPU monitoring for all processes
    for proc in psutil.process_iter():
        try:
            proc.cpu_percent()  # Initialize the monitoring
        except (psutil.NoSuchProcess, psutil.AccessDenied):
            pass
    
    # Wait a moment for CPU data to accumulate
    time.sleep(1)
    
    # Second pass: get actual CPU data
    for proc in psutil.process_iter(['pid', 'name', 'memory_percent']):
        try:
            cpu_usage = proc.cpu_percent()
            proc_info = proc.info.copy()
            proc_info['cpu_percent'] = cpu_usage
            processes.append(proc_info)
        except (psutil.NoSuchProcess, psutil.AccessDenied):
            pass
    
    # Sort by CPU usage
    processes.sort(key=lambda x: x['cpu_percent'] or 0, reverse=True)
    return processes[:limit]

def bytes_to_gb(bytes_value):
    """Convert bytes to gigabytes"""
    return bytes_value / (1024**3)

def print_system_report():
    """Print a formatted system report"""
    print("=" * 60)
    print(f"SYSTEM MONITOR REPORT - {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 60)
    
    # System info
    sys_info = get_system_info()
    print(f"\nSYSTEM INFO:")
    print(f"OS: {sys_info['system']} {sys_info['release']}")
    print(f"Machine: {sys_info['machine']}")
    print(f"Hostname: {sys_info['node']}")
    
    # CPU usage
    cpu_percent, cpu_count = get_cpu_usage()
    print(f"\nCPU USAGE:")
    print(f"Cores: {cpu_count}")
    print(f"Usage: {cpu_percent:.1f}%")
    
    # Memory usage (updated - shows detailed breakdown)
    memory = get_memory_usage()
    print(f"\nMEMORY USAGE:")
    print(f"Total: {bytes_to_gb(memory['total']):.1f} GB")
    print(f"Used: {bytes_to_gb(memory['used']):.1f} GB ({memory['percent']:.1f}%)")
    print(f"Available: {bytes_to_gb(memory['available']):.1f} GB")
    print(f"Active: {bytes_to_gb(memory['active']):.1f} GB")
    print(f"Inactive: {bytes_to_gb(memory['inactive']):.1f} GB")
    print(f"Wired: {bytes_to_gb(memory['wired']):.1f} GB")
    print(f"Free: {bytes_to_gb(memory['free']):.1f} GB")
    
    # Disk usage
#    disk = get_disk_usage()
#    print(f"\nDISK USAGE (Root):")
#    print(f"Total: {bytes_to_gb(disk['total']):.1f} GB")
#    print(f"Used: {bytes_to_gb(disk['used']):.1f} GB ({disk['percent']:.1f}%)")
#    print(f"Free: {bytes_to_gb(disk['free']):.1f} GB") 
    print(f"\nDISK USAGE (Root):")
    disk = psutil.disk_usage('/System/Volumes/Data')
    print(f"Total: {bytes_to_gb(disk.total):.1f} GB")
    print(f"Used: {bytes_to_gb(disk.used):.1f} GB ({disk.percent:.1f}%)")
    print(f"Free: {bytes_to_gb(disk.free):.1f} GB")

    # Top processes
    top_procs = get_top_processes()
    print(f"\nTOP 5 PROCESSES BY CPU:")
    print(f"{'PID':<8} {'Name':<25} {'CPU%':<8} {'Memory%':<8}")
    print("-" * 50)
    for proc in top_procs:
        print(f"{proc['pid']:<8} {proc['name'][:24]:<25} {proc['cpu_percent'] or 0:<8.1f} {proc['memory_percent'] or 0:<8.1f}")
    
    print("\n" + "=" * 60)

def main():
    """Main function"""
    try:
        print_system_report()
    except KeyboardInterrupt:
        print("\nMonitoring stopped by user.")
    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    main()
